channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pip:
      - sphinxemoji
      - pydata-sphinx-theme
      - sphinx-design
      - sphinxcontrib-needs
      - sphinxcontrib-plantuml
      - sphinxcontrib-programoutput
      - sphinx
      - myst-parser
      - numpydoc
